tf :
       terraform fmt

ti :
       terraform init

tp :
       terraform plan	  

ta :
       terraform init && terraform plan && terraform apply -auto-approve
	  
td :
       terraform init && terraform plan && terraform destroy -auto-approve

push :
       git add . && git commit -m "changes" && git push -u origin main
      